/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSettingsAccount: typeof import('./src/components/account-settings/AccountSettingsAccount.vue')['default']
    AccountSettingsNotification: typeof import('./src/components/account-settings/AccountSettingsNotification.vue')['default']
    AccountSettingsSecurity: typeof import('./src/components/account-settings/AccountSettingsSecurity.vue')['default']
    AnalyticsCongratulations: typeof import('./src/components/dashboard/AnalyticsCongratulations.vue')['default']
    AnalyticsFinanceTab: typeof import('./src/components/dashboard/AnalyticsFinanceTab.vue')['default']
    AnalyticsOrder: typeof import('./src/components/dashboard/AnalyticsOrder.vue')['default']
    AnalyticsOrderStatistics: typeof import('./src/components/dashboard/AnalyticsOrderStatistics.vue')['default']
    AnalyticsProfitReport: typeof import('./src/components/dashboard/AnalyticsProfitReport.vue')['default']
    AnalyticsRevenue: typeof import('./src/components/dashboard/AnalyticsRevenue.vue')['default']
    AnalyticsTotalRevenue: typeof import('./src/components/dashboard/AnalyticsTotalRevenue.vue')['default']
    AnalyticsTransactions: typeof import('./src/components/dashboard/AnalyticsTransactions.vue')['default']
    AuthProvider: typeof import('./src/components/authentication/AuthProvider.vue')['default']
    CardBasic: typeof import('./src/components/cards/card-basic/CardBasic.vue')['default']
    CardNavigation: typeof import('./src/components/cards/card-basic/CardNavigation.vue')['default']
    CardSolid: typeof import('./src/components/cards/card-basic/CardSolid.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CodeVariables: typeof import('./src/components/config/CodeVariables.vue')['default']
    DemoFormLayoutHorizontalForm: typeof import('./src/components/form-layouts/DemoFormLayoutHorizontalForm.vue')['default']
    DemoFormLayoutHorizontalFormWithIcons: typeof import('./src/components/form-layouts/DemoFormLayoutHorizontalFormWithIcons.vue')['default']
    DemoFormLayoutMultipleColumn: typeof import('./src/components/form-layouts/DemoFormLayoutMultipleColumn.vue')['default']
    DemoFormLayoutVerticalForm: typeof import('./src/components/form-layouts/DemoFormLayoutVerticalForm.vue')['default']
    DemoFormLayoutVerticalFormWithIcons: typeof import('./src/components/form-layouts/DemoFormLayoutVerticalFormWithIcons.vue')['default']
    DemoSimpleTableBasics: typeof import('./src/components/tables/DemoSimpleTableBasics.vue')['default']
    DemoSimpleTableDensity: typeof import('./src/components/tables/DemoSimpleTableDensity.vue')['default']
    DemoSimpleTableFixedHeader: typeof import('./src/components/tables/DemoSimpleTableFixedHeader.vue')['default']
    DemoSimpleTableHeight: typeof import('./src/components/tables/DemoSimpleTableHeight.vue')['default']
    DemoSimpleTableTheme: typeof import('./src/components/tables/DemoSimpleTableTheme.vue')['default']
    DialogCreateUsers: typeof import('./src/components/users/DialogCreateUsers.vue')['default']
    DialogInfoModels: typeof import('./src/components/config/DialogInfoModels.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    Filters: typeof import('./src/components/reports/filters.vue')['default']
    ModalCreateUsers: typeof import('./src/components/users/ModalCreateUsers.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PercentsForm: typeof import('./src/components/config/PercentsForm.vue')['default']
    PorcentsForm: typeof import('./src/components/config/PorcentsForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UsersFilters: typeof import('./src/components/users/UsersFilters.vue')['default']
    UsersTable: typeof import('./src/components/users/UsersTable.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
